language: generic
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
script:
- mkdir build
- cd build
- cmake .. && make
notifications:
  slack: iu8-22:zlUyTnBGmcpqkCgNXHMCCPzJ
